spring.config.activate.on-profile=local

spring.datasource.url=jdbc:postgresql://localhost:5432/orderflow
spring.datasource.username=orderflow
spring.datasource.password=orderflow123

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=orderflow
spring.rabbitmq.password=orderflow123
